# Telegram user ID of admins, or empty to assign no admin
admin_ids: ""

# Allowed USER Ids
allowed_user_ids: ""

# Budget configuration
user_budget: 1
guest_budget: 0.5
# Budget period: daily, monthly, total
budget_period: monthly
# Language to use for the bot, now supported: EN, RU
lang: EN

# Minimum role to show stats. Supported values: ADMIN, USER, GUEST
stats_min_role: ADMIN
token_price: 0.002

# Model configuration
type: openrouter
model: openai/gpt-4o-mini
base_url: https://openrouter.ai/api/v1
temperature: 0.7
top_p: 0.9

# Assistant configuration
assistant_prompt: |
  â€¢ Read the entire convo history line by line before answering. You are Assistant.


# Vision settings
vision: true
vision_prompt: Describe the image
vision_detail: low

